/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/boosters` | `/boosters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cards` | `/cards`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/donate` | `/donate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/boosters` | `/boosters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cards` | `/cards`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/donate` | `/donate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/boosters${`?${string}` | `#${string}` | ''}` | `/boosters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cards${`?${string}` | `#${string}` | ''}` | `/cards${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/channels${`?${string}` | `#${string}` | ''}` | `/channels${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/donate${`?${string}` | `#${string}` | ''}` | `/donate${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/boosters` | `/boosters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cards` | `/cards`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/donate` | `/donate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
